### ISSUE TITLE
Can I build a single windows binary

### ISSUE THREAD

**Issue by vikram-rawat** [revel/cmd#166]
This feature can help me run it on a windows server. Or create basic app for windows user.

Can I build a single binary for windows. Which will run without golang installed. 

If so please tell me how.

**Comment by notzippy** [comment]
Yes, with cavets. You can build to a single binary using the tool [build or package](http://revel.github.io/manual/tool.html#build) option. This creates a single executable for the application - but the application still needs the configuration file and the template files. We are looking into ways that everything could be bundled as one (or maybe two) files.

**Comment by rami-dabain** [comment]
@notzippy go-bind as a neat solution

**Comment by notzippy** [comment]
Seems like most of the solutions like gobind, packr convert the code into Go files in order to store it in the executable. IMO it may be best to package the data using a single resource file and a single binary file.

**Comment by notzippy** [comment]
Currently revel requires the package to be unpacked in order to run - For best practices it should be used running on a server, then multiple people can access it from a single point. So if you are running it in your organization it should be placed on a server so that everyone can access easily without installing or running anything on their workstations..
