### ISSUE TITLE
Support go modules (go.mod) instead of dep

### ISSUE THREAD

**Issue by ptman** [revel/cmd#177]
I hope this is the right place for this ticket

**Comment by eparziale** [comment]
@notzippy  
Are there any plans to update revel cmd to support projects that use go modules instead of dep?

My team has used revel for the past year and has been very happy with the framework.

Until recently, we didn't need a proper dependency management tool like dep or go modules. (Instead we just maintained a list of required packages, and ran go get <pkg name> to fetch HEAD of each package)

However, we're now at a point where certain upstream dependency projects are forcing us to move to a dependency management tool. We could migrate to dep, but go modules seems like the direction that the go ecosystem is moving.

How much effort would be required to update revel cmd tool to support go modules?

FYI - I tried creating a basic revel application using go modules, but it failed to work 
---------------------------
For reference - Here's a link to that  sample barebones revel skeleton project that works when **NOT** using go-modules, but breaks when tweaked to use go modules: 

**Link to Working Revel skeleton App repo:** https://github.com/ejparz/revel-example
**Healthy CircleCi start of app: ** https://circleci.com/gh/ejparz/revel-example/5



**Small pull request on the same repo, adjusting the app to use go modules:** https://github.com/ejparz/revel-example/pull/1/files

**Corresponding failed CircleCi Build (Build fails because revel cmd is incompatible with go modules):** https://circleci.com/gh/ejparz/revel-example/6



-------

_**If there are no plans to update revel to support go modules soon, then we'll adjust our build process to use dep instead :( **_

**Comment by ptman** [comment]
We are using dep. I don't think revel will work with go modules currently. But @notzippy is working on go modules support and go modules can migrate from dep.

**Comment by eparziale** [comment]
Understood. We'll use dep.

Thanks for the info!

**Comment by ptman** [comment]
#180
